# build environment
FROM node:16-alpine as frontend-build

ARG BUILD_ENVIRONMENT

WORKDIR /opt/eslo/frontend

COPY . /opt/eslo/frontend

RUN npm install

RUN npm run build-$BUILD_ENVIRONMENT

# server environment
FROM nginx:alpine

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

## Remove default conf
RUN rm /etc/nginx/conf.d/default.conf
# RUN rm etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/conf.d/eslo.com.conf


COPY --from=frontend-build /opt/eslo/frontend/dist /usr/share/nginx/html

ENV PORT 80

EXPOSE 4200 80

CMD ["nginx", "-g", "daemon off;"]
