# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  ##### FRONTEND #####
  # Build the frontend container image
  - id: "build-frontend"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BUILD_ENVIRONMENT=production",
        "-f",
        ./Dockerfile-cicd,
        "-t",
        "${_DOCKER_REGISTRY_FULL_PATH}/eslo-frontend:$SHORT_SHA-prod",
        ".",
      ]
    dir: "frontend"
    waitFor: ["-"]

  # Push the frontend container image to Container Registry
  - id: "push-frontend"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_DOCKER_REGISTRY_FULL_PATH}/eslo-frontend:$SHORT_SHA-prod"]
    dir: "frontend"
    waitFor:
      - "build-frontend"

  ##### Terraform (IaC) #####
  # Deploy any changes in infrastrucure
  # Also, deploy apps with new images (commit SHA tags)

  # [START tf set up]
  - id: "tf-setup"
    name: ${_DOCKER_REGISTRY_FULL_PATH}/terraform:0.14.7
    dir: "terraform"
    entrypoint: /bin/bash
    secretEnv: ["BACKEND_TF_VARS"]
    args:
      - -c
      - |
        echo "$$BACKEND_TF_VARS" > ./envs/production/secrets.auto.tfvars
    waitFor: ["-"]

  # [START tf-init]
  - id: "tf-init"
    name: ${_DOCKER_REGISTRY_FULL_PATH}/terraform:0.14.7
    dir: "terraform"
    entrypoint: /bin/bash
    args:
      - -c
      - |
        ./tf-wrapper.sh init production
    waitFor:
      - "tf-setup"

  # [START tf-plan]
  - id: "tf-plan"
    name: ${_DOCKER_REGISTRY_FULL_PATH}/terraform:0.14.7
    dir: "terraform"
    entrypoint: /bin/bash
    env:
      - "TF_VAR_backend_image_tag=$SHORT_SHA"
      - "TF_VAR_frontend_image_tag=$SHORT_SHA-prod"
      - "TF_VAR_iam_agent_image_tag=$SHORT_SHA"
    args:
      - -c
      - |
        ./tf-wrapper.sh plan production
    waitFor:
      - "tf-init"

  # [START tf-apply]
  - id: "tf-apply"
    name: ${_DOCKER_REGISTRY_FULL_PATH}/terraform:0.14.7
    dir: "terraform"
    entrypoint: /bin/bash
    env:
      - "TF_VAR_backend_image_tag=$SHORT_SHA"
      - "TF_VAR_frontend_image_tag=$SHORT_SHA-prod"
      - "TF_VAR_iam_agent_image_tag=$SHORT_SHA"
    args:
      - -c
      - |
        ./tf-wrapper.sh apply production
    waitFor:
      - "tf-plan"
      - "push-frontend"
timeout: 2700s
# TODO: secret project is hard-coded for now
availableSecrets:
  secretManager:
    - versionName: projects/prj-p-secrets-4f8e/secrets/eslo-platform-backend-tf-vars/versions/latest
      env: BACKEND_TF_VARS
