# build environment
FROM node:16-slim as backend-build

RUN apt-get update
RUN apt-get install -y openssl

WORKDIR /opt/eslo/backend

COPY . /opt/eslo/backend

RUN npm install

RUN npm run build


# server environment
FROM node:16-slim

RUN apt-get update
RUN apt-get install -y openssl

WORKDIR /opt/eslo/backend

COPY --from=backend-build /opt/eslo/backend/dist ./app
COPY --from=backend-build /opt/eslo/backend/package.json .
COPY --from=backend-build /opt/eslo/backend/scripts/entrypoint.sh entrypoint.sh
COPY --from=backend-build /opt/eslo/backend/node_modules/ ./node_modules

RUN chmod 755 entrypoint.sh

ENV PORT 3000

EXPOSE 3000

# entrypoint with default command to run server.
# other options are: deploy-db:prod | seed-db
ENTRYPOINT ["./entrypoint.sh"]
# CMD ["npm", "run", "serve:prod"]
