# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 1200s
substitutions:
  _POLICY_REPO: '' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator
steps:
- id: 'setup'
  name: gcr.io/$PROJECT_ID/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
    echo "Setting up gcloud for impersonation"
    gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
    echo "Adding bucket information to backends"
    for i in `find -name 'backend.tf'`; do sed -i 's/UPDATE_ME/${_STATE_BUCKET_NAME}/' $i; done

# [START tf-init]
- id: 'tf init'
  name: gcr.io/${PROJECT_ID}/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
      ./tf-wrapper.sh init ${BRANCH_NAME}

# [START tf-plan]
- id: 'tf plan'
  name: gcr.io/${PROJECT_ID}/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
      ./tf-wrapper.sh plan ${BRANCH_NAME}

# [START tf-validate]
- id: 'tf validate'
  name: gcr.io/${PROJECT_ID}/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
      ./tf-wrapper.sh validate ${BRANCH_NAME} ${_POLICY_REPO}

# [START tf-apply]
- id: 'tf apply'
  name: gcr.io/${PROJECT_ID}/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
      ./tf-wrapper.sh apply ${BRANCH_NAME}

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/apply/${BUILD_ID}'
    paths: ['cloudbuild-tf-apply.yaml', 'tmp_plan/*.tfplan']
